services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=simulacred
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=simulacred123
    ports:
      - "5432:5432"